const CREATED = 201;
const BAD_REQUEST_ERROR_STATUS = 400;
const NOT_FOUND_ERROR_STATUS = 404;
const INTERNAL_SERVER_ERROR_STATUS = 500;

module.exports = {
  CREATED,
  BAD_REQUEST_ERROR_STATUS,
  NOT_FOUND_ERROR_STATUS,
  INTERNAL_SERVER_ERROR_STATUS,
};
